---
- name: Template out Vagrant file
  ansible.builtin.template:
    src: Vagrantfile.j2
    dest: "{{ local_project_directory }}/infra/Vagrantfile"
    owner: "{{ lookup('ansible.builtin.env', 'USER') }}"
    group: "staff"
    mode: "0644"

- name: Start vagrant hosts
  ansible.builtin.command:
    cmd: "vagrant up"
  register: my_output
  changed_when: my_output.rc != 0
