---

- name: Install Vagrant
  community.general.homebrew:
    update_homebrew: true
    name:
      - hashicorp/tap/hashicorp-vagrant
    state: present

- name: Start vagrant hosts
  ansible.builtin.command:
    cmd: "vagrant up"
  register: my_output
  changed_when: my_output.rc != 0
