---
- name: Destroy environment
  hosts: localhost
  vars_files:
    - "{{ ansible_env.PWD }}/vars/main.yml"
  tasks:
    - name: Destroy Vagrant
      ansible.builtin.include_role:
        name: destroy_vagrant
