---
- name: Destroy environment
  hosts: localhost
  vars_files:
    - "{{ lookup('ansible.builtin.env', 'HOME') }}/workspace/projects/ansible-server/infra/vars/main.yml"
  tasks:
    - name: Destroy Vagrant
      ansible.builtin.include_role:
        name: destroy_vagrant
