VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Use the same key for each machine
  config.ssh.insert_key = false

  config.vm.define "vagrant1" do |vagrant1|
    vagrant1.vm.box = "ubuntu/focal64"
    vagrant1.vm.network "forwarded_port", guest:22, host: 2230
    vagrant1.vm.network "forwarded_port", guest:8000, host: 8001
    # vagrant1.vm.network "private_network", ip: "10.2.2.200"
  end
end