---
- name: Install postgresql
  become: true
  become_user: root
  ansible.builtin.apt:
    update_cache: true
    name:
      - postgresql
      - postgresql-contrib
      - acl
    state: present

- name: Install pip3
  become: true
  become_user: root
  ansible.builtin.apt:
    name:
      - python3-pip
    state: present

- name: Make sure psycopg2-binary is installed
  become: true
  become_user: root
  ansible.builtin.pip:
    name: psycopg2-binary
    state: present
