app_name: webserver
local_project_directory: "{{ lookup('ansible.builtin.env', 'HOME') }}/workspace/projects/ansible-server"
host_project_directory: "/home/{{ owner }}/backend"
host_virtual_env_bin_directory: "{{ host_project_directory }}/venv/bin"
owner: vagrant
group: vagrant
