app_name: webserver
last_octet: 200
owner: vagrant
group: vagrant
ssh_host: 2230
local_project_directory: "{{ lookup('ansible.builtin.env', 'HOME') }}/workspace/projects/ansible-server"

################################
#  Frontend reverse proxy
################################
frontend_reverse_proxy_name: "frontendReverseProxy"
frontend_reverse_proxy_ip_address: "10.2.2.{{ last_octet }}"
frontend_reverse_proxy_ssh_host: "{{ ssh_host }}"

################################
#  Nomad
################################
nomad_name: "nomadLoadBalancer"
nomad_ip_address: "10.2.2.{{ last_octet + 1 }}"
nomad_ssh_host: "{{ ssh_host + 1 }}"

################################
#  Frontend
################################
frontend_name: "frontendWebApp"
frontend_ip_address: "10.2.2.{{ last_octet + 2 }}"
frontend_host_project_directory: "/home/{{ owner }}/frontend"
frontend_docker_image: "nimzy/next-demo-app"
frontend_ssh_host: "{{ ssh_host + 2 }}"

################################
#  Backend load balancer
################################
backend_load_balancer_name: "backendLoadBalancer"
backend_load_balancer_ip_address: "10.2.2.{{ last_octet + 3 }}"
backend_load_balancer_ssh_host: "{{ ssh_host + 3 }}"

################################
#  Backend Django application
################################
server_a_name: "serverA"
server_b_name: "serverB"
server_a_ip_address: "10.2.2.{{ last_octet + 4 }}"
server_b_ip_address: "10.2.2.{{ last_octet + 5 }}"
server_a_ssh_host: "{{ ssh_host + 4 }}"
server_b_ssh_host: "{{ ssh_host + 5 }}"
backend_host_project_directory: "/home/{{ owner }}/backend"
backend_host_settings_path: "{{ backend_host_project_directory }}/django_project/settings.py"
backend_host_virtual_env_bin_directory: "{{ backend_host_project_directory }}/venv/bin"
