---
- name: Run the equivalent of "apt-get update"
  become: true
  become_user: root
  ansible.builtin.apt:
    update_cache: true

- name: Copy Django project
  ansible.posix.synchronize:
    src: "{{ project_directory }}/backend/"
    dest: "/home/{{ owner }}/backend/"
    rsync_opts:
      - "--exclude={{ project_directory }}/backend/.venv"
      - "--exclude={{ project_directory }}/backend/db.sqlite3"

- name: Install pip3
  become: true
  become_user: root
  ansible.builtin.apt:
    name:
      - python3-pip
      - python3.8-venv
    state: present

- name: Install virtualenv via pip3
  become: true
  become_user: root
  ansible.builtin.pip:
    name: virtualenv
    executable: "{{ pip_executable }}"

- name: Install dependencies
  ansible.builtin.pip:
    requirements: "/home/{{ owner }}/backend/requirements.txt"
    virtualenv: "/home/{{ owner }}/backend/venv"

# - name: Run Django server
#   ansible.builtin.shell:
#     cmd: "source /home/{{ owner }}/backend/venv/bin/activate && python3 manage.py runserver"
#   register: source_output
#   changed_when: source_output.rc != 0
