---
- name: Template gunicorn config file
  ansible.builtin.template:
    src: gunicorn_config.py.j2
    dest: "{{ backend_host_project_directory }}/gunicorn_config.py"
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: "0644"

- name: Template gunicorn systemd file
  become: true
  become_user: root
  ansible.builtin.template:
    src: gunicorn.service.j2
    dest: "/etc/systemd/system/{{ service_name }}"
    owner: "{{ owner }}"
    group: "{{ group }}"
    mode: "0644"
