---
# This example uses the 'priv' argument which is deprecated.
# You should use the 'postgresql_privs' module instead.
- name: Connect to acme database and set user's password with no expire date
  become: true
  become_user: postgres
  become_method: ansible.builtin.sudo
  community.postgresql.postgresql_user:
    # db: acme
    name: django
    password: mysupersecretword
    expires: infinity
    login_user: postgres
    login_password: password

- name: Create a new database with name "acme"
  become: true
  become_user: postgres
  become_method: ansible.builtin.sudo
  community.postgresql.postgresql_db:
    name: acme
    login_user: postgres
    login_password: password

# Note that here "db: postgres" specifies the database to connect to, not the
# database to grant privileges on (which is specified via the "objs" param)
- name: GRANT ALL PRIVILEGES ON DATABASE library TO librarian
  community.postgresql.postgresql_privs:
    db: acme
    privs: ALL
    type: database
    obj: table
    role: django
